import React from "react";
import {
  AbsoluteFill,
  Audio,
  Img,
  interpolate,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";

import { Glass } from "./Glass";
import { Action, Composer, Ghost, type Provider } from "./Sentence";
import {
  C,
  CLASH,
  easeIn,
  easeOut,
  easeInOut,
  fullLogo,
  labelStyle,
  LOGO_FULL,
  T,
  WORD_SPACING,
} from "./theme";

/**
 * 20 seconds of the IOU composer, cut on a 120bpm grid.
 *
 * 60fps, so one beat is exactly 30 frames and every shot boundary below lands
 * on one. The soundtrack (public/audio/promo-score.wav, generated by
 * video/score.mjs) is cut to the same grid and to the same frame numbers, so
 * retiming a shot here means moving the matching cue there.
 *
 * The composer itself is NOT wrapped in <Sequence>. Its state is one continuous
 * function of the absolute frame, because the sentence is meant to read as a
 * single unbroken take from the first keystroke to the settled stamp — a
 * Sequence per shot would remount it and lose that.
 */

const COLD_OPEN = 0;
const TYPE = 90; //     1.5s — the sentence writes itself
const FLIP = 330; //    5.5s — the verb is tapped
const ANYONE = 480; //  8.0s — four namespaces
const SETTLE = 720; //  12.0s — money moves
const OUTRO = 900; //   15.0s — the composer leaves
const MAINNET = 930; //  15.5s — the news, one bar of its own
const ENDCARD = 1080; // 18.0s — the lockup
const END = 1200; //    20.0s

/** The composer column's left edge, and the rail's inset. */
const MARGIN = 150;

const HANDLE = "dani";
const EMAIL = "dani@gmail.com";
const ADDRESS = "0xEE42a492B183CdFf04439F2Cb6A9c49F857F70AC";
/** What .iou-compact draws in the full address's place. The value is untouched. */
const ADDRESS_SHORT = "0xEE42…70AC";
const AMOUNT = "42";
/** One of the real REASONS from app/IouClient.tsx. */
const REASON = "last night's ramen";

/** The mainnet card, one masked word per box so they can stagger. */
const MAINNET_WORDS: { text: string; accent?: boolean }[] = [
  { text: "Now" },
  { text: "live" },
  { text: "on" },
  { text: "mainnet", accent: true },
];

const NAMESPACES: { key: Provider; label: string }[] = [
  { key: "x", label: "X" },
  { key: "discord", label: "Discord" },
  { key: "email", label: "Email" },
  { key: "wallet", label: "Wallet" },
];

/** 0 → 1 across a frame range, clamped both ends. */
const ramp = (frame: number, from: number, to: number, easing = easeOut) =>
  interpolate(frame, [from, to], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing,
  });

/** Reveals `text` one character at a time. Negative `perChar` deletes it instead. */
const typing = (frame: number, text: string, from: number, perChar: number) => {
  const n = Math.floor((frame - from) / Math.abs(perChar));
  if (frame < from) return perChar > 0 ? "" : text;
  const shown = perChar > 0 ? n : text.length - n;
  return text.slice(0, Math.max(0, Math.min(text.length, shown)));
};

/**
 * Which namespace the who-slot is holding, and what is typed into it.
 *
 * The app clears a field by select-all-and-overtype for anything long, and
 * backspaces short values; both are reproduced, because a 42-character address
 * deleted one character at a time would eat two full seconds of an 18-second cut.
 */
const whoAt = (frame: number): { provider: Provider; target: string } => {
  if (frame < 516) return { provider: "x", target: typing(frame, HANDLE, 160, 15) };
  // X → Discord: backspaced, because four characters is quick
  if (frame < 528) return { provider: "x", target: typing(frame, HANDLE, 516, -3) };
  if (frame < 564) return { provider: "discord", target: typing(frame, HANDLE, 528, 3) };
  // Discord → email: select-all, overtype
  if (frame < 570) return { provider: "discord", target: "" };
  // Typed fast enough to land on the complete address well before the cut. An
  // email frozen mid-domain reads as a typo'd TLD rather than as typing.
  if (frame < 636) return { provider: "email", target: typing(frame, EMAIL, 570, 2.4) };
  if (frame < 642) return { provider: "email", target: "" };
  // The address types out in full, which is what forces the sentence to scale
  // down to hold it — then .iou-compact collapses it and the sentence springs back.
  if (frame < 690) return { provider: "wallet", target: typing(frame, ADDRESS, 642, 1.15) };
  return { provider: "wallet", target: ADDRESS_SHORT };
};

export const Promo: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const { provider, target } = whoAt(frame);

  // The flip, both ways. Heavily damped — a sentence that bounces reads as a
  // toy, and this one is moving money.
  const flipOut = spring({ frame, fps, delay: 354, durationInFrames: 44, config: { damping: 200 } });
  const flipBack = spring({ frame, fps, delay: 726, durationInFrames: 40, config: { damping: 200 } });
  const flip = flipOut * (1 - flipBack);

  const amount = frame < 248 ? "" : typing(frame, AMOUNT, 248, 14);

  // The settle press, and what it throws out.
  const press = interpolate(frame, [770, 776, 790], [0, 1, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: easeOut,
  });
  const settled = ramp(frame, 832, 852);

  const exit = ramp(frame, OUTRO, OUTRO + 26, easeIn);
  const composerOpacity = frame < TYPE ? 0 : 1 - exit;
  const actionLabel = flip > 0.5 ? "send the ask" : "settle";

  // The camera. A slow push across the whole take, plus a small punch-in on
  // the settle press, anchored on the sentence so the push moves toward the
  // words, not toward empty glass. The exit pulls back and blurs, which hands
  // off to the headline instead of cutting to it.
  const push = interpolate(frame, [TYPE, OUTRO], [1, 1.045], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const punch = spring({ frame, fps, delay: 772, durationInFrames: 36, config: { damping: 14, mass: 0.6 } });
  const punchScale = 1 + punch * 0.018 * (1 - ramp(frame, 800, 860));
  const camera = push * punchScale * (1 - exit * 0.06);

  // The pulse from the stamp: two rings in --success, the way a confirmation
  // lands on a payment sheet.
  const pulse = (delay: number) => ramp(frame, 834 + delay, 894 + delay, easeOut);

  const logoReveal = ramp(frame, 0, 62, easeOut);
  const logoExit = ramp(frame, 56, 92, easeIn);
  const logoFull = fullLogo(1100);
  const endLogo = fullLogo(760);

  return (
    <AbsoluteFill style={{ backgroundColor: C.ground }}>
      <Glass introFrames={90} />
      {/* The score — music and sound design, already mixed and mastered to one
          18s master by video/score.mjs, which is why this is a single tag and
          not a cue sheet. Cue frames live in that file and are keyed to the
          frame numbers below, so retiming a shot means editing both. */}
      <Audio src={staticFile("audio/promo-score.wav")} />

      {/* ── 01 · cold open ────────────────────────────────────────────────
          The full lockup (splitsydarkfull.png), not a mark beside typeset
          "Splitsy": the wordmark is drawn, not set, and setting it in Clash by
          hand approximates a logo instead of showing one. The source carries a
          lot of transparent padding around the art — its content box is
          1386×456 inside 1536×1024 — so it is sized by the art's real aspect and
          cropped to it, or the lockup sits visually high and small. */}
      <AbsoluteFill style={{ alignItems: "center", justifyContent: "center" }}>
        <div
          style={{
            opacity: logoReveal * (1 - logoExit),
            transform: `translateY(${-logoExit * 90}px) scale(${
              1.16 - logoReveal * 0.16 + logoExit * 0.06
            })`,
          }}
        >
          {/* clip-path wipes the lockup in from the left while its own glow
              trails, which is the reveal — no separate light-sweep element
              needed, and nothing crosses the letters to read as a glitch. */}
          <div
            style={{
              ...logoFull.box,
              overflow: "hidden",
              clipPath: `inset(0 ${(1 - ramp(frame, 4, 44, easeOut)) * 100}% 0 0)`,
            }}
          >
            <Img
              src={staticFile(LOGO_FULL.src)}
              style={{
                ...logoFull.img,
              }}
            />
          </div>
        </div>
      </AbsoluteFill>

      {/* ── the composer, frames 90 → 900 ───────────────────────────────── */}
      <AbsoluteFill
        style={{
          opacity: composerOpacity,
          // Origin on the sentence, not the frame centre: a push anchored at
          // 50% 50% drifts the type off to the left as it grows.
          transformOrigin: "22% 46%",
          // The push, plus a very slow drift on two primes. The drift is what
          // keeps the frame from ever being pixel-identical to the last one —
          // a dead-still camera is the single biggest "screen recording" tell.
          transform: `scale(${camera}) translate3d(${Math.sin(frame / 46) * 5}px, ${Math.cos(frame / 58) * 3}px, 0)`,
          filter: exit > 0 ? `blur(${exit * 10}px)` : undefined,
        }}
      >
        {/* .iou-rail — "← receipts" one side, the network the other. Both are the
            app's own strings; the right-hand one is what a mainnet build says. */}
        <div
          style={{
            position: "absolute",
            top: 60,
            left: MARGIN,
            right: MARGIN,
            display: "flex",
            justifyContent: "space-between",
            opacity: ramp(frame, 92, 124),
            ...labelStyle(),
          }}
        >
          <span>← receipts</span>
          <span>usdc on arc</span>
        </div>

        <div style={{ position: "absolute", top: 410, left: MARGIN }}>
          <Composer
            flip={flip}
            provider={provider}
            target={target}
            amount={amount}
            rule={ramp(frame, 280, 320)}
            lift={-ramp(frame, 820, 844) * 26}
            caret={frame > 150 && frame < 700 && Math.floor(frame / 24) % 2 === 0}
            verbFocus={ramp(frame, 338, 352) * (1 - ramp(frame, 440, 462))}
            print={[
              ramp(frame, 100, 122),
              ramp(frame, 116, 138),
              ramp(frame, 134, 156),
              ramp(frame, 226, 248),
            ]}
          />
        </div>

        {/* the note line's ghost — the app writes it per character, so this does
            too. It stays up through the settle: the app never clears it, and
            dropping it early left a dead band between the rule and the action. */}
        <div style={{ position: "absolute", top: 636, left: MARGIN }}>
          <Ghost text={REASON} chars={Math.floor(ramp(frame, 296, 356) * REASON.length)} />
        </div>

        {/* .iou-meta — "on x" only while the target does not already name its own
            namespace, which is exactly the app's rule: an email and a 0x address do. */}
        <div
          style={{
            position: "absolute",
            top: 710,
            left: MARGIN,
            display: "flex",
            gap: 40,
            opacity: ramp(frame, 250, 280),
            ...labelStyle(),
          }}
        >
          {provider === "x" || provider === "discord" ? <span>on {provider}</span> : null}
          <span>as @you</span>
        </div>

        <div style={{ position: "absolute", top: 776, left: MARGIN }}>
          <Action label={actionLabel} opacity={ramp(frame, 258, 288)} press={press} />
          {/* The blocks the send throws out. They travel along the action's own
              baseline, starting clear of the word: a block crossing the letters
              reads as a glitch, not as a send. */}
          {[0, 1, 2].map((i) => {
            const go = ramp(frame, 778 + i * 8, 846 + i * 8, easeOut);
            return (
              <div
                key={i}
                style={{
                  position: "absolute",
                  top: T.action * 0.44,
                  left: 370,
                  width: 14,
                  height: 14,
                  background: C.accent,
                  opacity: go > 0 && go < 1 ? 1 : 0,
                  transform: `translateX(${go * 420}px)`,
                }}
              />
            );
          })}
        </div>

        {/* ── 04 · the four namespaces ─────────────────────────────────── */}
        <div
          style={{
            position: "absolute",
            top: 890,
            left: MARGIN,
            display: "flex",
            gap: 46,
            opacity: ramp(frame, 486, 516) * (1 - ramp(frame, 700, 720)),
          }}
        >
          {NAMESPACES.map((ns) => (
            <span key={ns.key} style={labelStyle(ns.key === provider ? C.ink : C.rule)}>
              {ns.label}
            </span>
          ))}
        </div>

        {/* ── 05 · settled ─────────────────────────────────────────────── */}
        <div style={{ position: "absolute", top: 890, left: MARGIN, opacity: settled }}>
          {/* Two confirmation rings off the stamp as it lands */}
          {[0, 10].map((d) => (
            <div
              key={d}
              style={{
                position: "absolute",
                left: 140 - 60,
                top: 22 - 60,
                width: 120,
                height: 120,
                borderRadius: "50%",
                border: `2px solid ${C.success}`,
                opacity: pulse(d) > 0 && pulse(d) < 1 ? (1 - pulse(d)) * 0.7 : 0,
                transform: `scale(${0.4 + pulse(d) * 3.2})`,
              }}
            />
          ))}
          {/* .settlement-stamp, verbatim: −7°, a 2px success keyline, 850 weight */}
          <div
            style={{
              width: "fit-content",
              transform: `rotate(-7deg) scale(${interpolate(settled, [0, 1], [2.4, 1])})`,
              border: `2px solid ${C.success}`,
              borderRadius: 6,
              color: C.success,
              padding: "8px 16px",
              fontFamily: CLASH,
              wordSpacing: WORD_SPACING,
              fontWeight: 700,
              fontSize: T.label,
              letterSpacing: "0.08em",
              textTransform: "uppercase",
            }}
          >
            Settled on Arc
          </div>
        </div>
      </AbsoluteFill>

      {/* ── 03 · what the flip means, for a muted viewer ────────────────── */}
      <div
        style={{
          position: "absolute",
          top: 890,
          left: MARGIN,
          opacity: ramp(frame, 400, 428) * (1 - ramp(frame, 468, 486)),
          ...labelStyle(C.ink),
        }}
      >
        Ask for it, or send it
      </div>

      {/* ── 06 · now live on mainnet ─────────────────────────────────────
          The news the teaser exists to deliver, so it gets a bar to itself
          (930 → 1080) and the endcard moves to the bar after it.

          Set as four masked words rather than one line of text: each one is
          wrapped in an overflow:hidden box and slides up out of it on a
          stagger, which is the same reveal the headline in video/motion uses
          (`.headline .line { overflow: hidden }`). One opacity fade on the
          whole line would be cheaper and would read as a slide deck.

          The dot and its two rings are the settlement stamp's confirmation
          pulse at a fifth of the size — deliberately. The motif that said
          "this payment settled" now says "the network is up", which ties the
          two payoffs together more cheaply than any transition could. */}
      <AbsoluteFill style={{ alignItems: "center", justifyContent: "center" }}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            // The whole card lifts away into the endcard rather than crossfading
            // with it: two centred cards dissolving through each other read as
            // a mistake, because for six frames the logo sits inside the type.
            opacity: ramp(frame, MAINNET, MAINNET + 8) * (1 - ramp(frame, 1044, 1078, easeIn)),
            transform: `translateY(${-ramp(frame, 1044, 1078, easeIn) * 52}px)`,
          }}
        >
          {/* the live signal */}
          <div style={{ position: "relative", height: 34, marginBottom: 38 }}>
            {[0, 26].map((delay) => {
              const pulse = ramp(frame, MAINNET + 4 + delay, MAINNET + 76 + delay, easeOut);
              return (
                <div
                  key={delay}
                  style={{
                    position: "absolute",
                    left: -28,
                    top: -21,
                    width: 60,
                    height: 60,
                    borderRadius: "50%",
                    border: `2px solid ${C.success}`,
                    opacity: pulse > 0 && pulse < 1 ? (1 - pulse) * 0.62 : 0,
                    transform: `scale(${0.35 + pulse * 2.1})`,
                  }}
                />
              );
            })}
            <div
              style={{
                position: "absolute",
                left: -7,
                top: 0,
                width: 14,
                height: 14,
                borderRadius: "50%",
                background: C.success,
                // The glow is what makes it read as lit rather than printed.
                boxShadow: `0 0 22px ${C.success}`,
                transform: `scale(${interpolate(ramp(frame, MAINNET, MAINNET + 20), [0, 1], [0, 1])})`,
              }}
            />
          </div>

          <div
            style={{
              display: "flex",
              // A flex gap, not wordSpacing: the words are separate boxes now,
              // so the space between them has to be laid out rather than typeset.
              gap: "0.3em",
              fontFamily: CLASH,
              fontWeight: 300,
              fontSize: 136,
              letterSpacing: "-0.03em",
              lineHeight: 1,
            }}
          >
            {MAINNET_WORDS.map((word, i) => {
              const rise = ramp(frame, MAINNET + 12 + i * 6, MAINNET + 54 + i * 6);
              return (
                <span
                  key={word.text}
                  style={{
                    display: "inline-block",
                    overflow: "hidden",
                    // The mask has to clear the descender line or a future copy
                    // change with a "g" in it gets its tail shaved off; the
                    // negative margin keeps the padding out of the layout.
                    paddingBottom: "0.14em",
                    marginBottom: "-0.14em",
                  }}
                >
                  <span
                    style={{
                      display: "inline-block",
                      color: word.accent ? C.accent : C.ink,
                      transform: `translateY(${(1 - rise) * 112}%)`,
                    }}
                  >
                    {word.text}
                  </span>
                </span>
              );
            })}
          </div>

          {/* The rule draws out from the centre and is the card's last beat and
              its only piece of geometry — the label that used to sit under it is
              gone, so the rule closes the card rather than introducing anything.
              Same 2px keyline weight as the composer's rule and the stamp's. */}
          <div
            style={{
              width: 560,
              height: 2,
              marginTop: 52,
              background: C.rule,
              transform: `scaleX(${ramp(frame, MAINNET + 38, MAINNET + 82)})`,
            }}
          />
        </div>
      </AbsoluteFill>

      <AbsoluteFill
        style={{
          alignItems: "center",
          justifyContent: "center",
          opacity: ramp(frame, ENDCARD, ENDCARD + 30),
        }}
      >
        <div
          style={{
            transform: `translateY(${(1 - ramp(frame, ENDCARD, ENDCARD + 30)) * 40}px)`,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          {/* Use the actual full lockup here too. The compact mark is reserved
              for small in-product moments; the endcard deserves the drawn logo. */}
          <div
            style={{
              ...endLogo.box,
              overflow: "hidden",
              transform: `rotate(${(1 - ramp(frame, ENDCARD, ENDCARD + 40)) * -3}deg) scale(${interpolate(
                ramp(frame, ENDCARD, ENDCARD + 40),
                [0, 1],
                [0.86, 1],
              )})`,
              clipPath: `inset(0 ${(1 - ramp(frame, ENDCARD + 6, ENDCARD + 42)) * 100}% 0 0)`,
            }}
          >
            <Img
              src={staticFile(LOGO_FULL.src)}
              style={{
                ...endLogo.img,
              }}
            />
          </div>
          {/* Staggered in behind the lockup rather than with it: the wipe does
              not start until ENDCARD + 6, so a label on the container's own fade
              is fully readable while the logo is still a blank box. */}
          <div
            style={{
              marginTop: 50,
              opacity: ramp(frame, ENDCARD + 30, ENDCARD + 56),
              ...labelStyle(C.ink, 30),
            }}
          >
            utilizing programmable money on Arc
          </div>
          <div
            style={{
              marginTop: 20,
              opacity: ramp(frame, ENDCARD + 40, ENDCARD + 66),
              ...labelStyle(C.accentStrong, 26),
            }}
          >
            splitsy.xyz
          </div>
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
